### ISSUE TITLE
Javadoc generation failing: cannot resolve bouncycastle

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.common#83]
See https://download.eclipse.org/eclipse/downloads/drops4/I20221003-1800/compilelogs/platform.doc.isv.javadoc.txt and later

**Comment by mickaelistria** [comment]
Should be fixed with #84. Let's wait for next I-Build.

**Comment by akurtakov** [comment]
This is not enough. I tried locally and it still failed. Dependencies in dependencies.dir have the maven artifactIds which are bcpg-jdk18on_*.jar and bcprov-jdk18on_*.jar

**Comment by mickaelistria** [comment]
I didn't manage to test this locally as build was complaining about other stuff; but I'm pretty sure you're right. Are you willing to submit a PR?
